"""empty message

Revision ID: 2ad9bd28b215
Revises: 
Create Date: 2025-04-03 15:05:55.356763

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ad9bd28b215'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_auth_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testfield', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_auth_code', schema=None) as batch_op:
        batch_op.drop_column('testfield')

    # ### end Alembic commands ###
