"""empty message

Revision ID: e89756857c7a
Revises: 2ad9bd28b215
Create Date: 2025-04-03 15:15:51.898252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e89756857c7a'
down_revision = '2ad9bd28b215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_auth_code', schema=None) as batch_op:
        batch_op.drop_column('testfield')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('spotify_auth_code', schema=None) as batch_op:
        batch_op.add_column(sa.Column('testfield', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
